package ru.pixelmongo.pixelmongo.model.dao.primary;

public enum StaffDisplayBackground {

    WHITE,
    BLUE,
    LIGHT_BLUE,
    DARK_BLUE,
    CYAN,
    GREEN,
    LIGHT_GREEN,
    DARK_GREEN,
    RED,
    LIGHT_RED,
    DARK_RED,
    GRAY,
    LIGHT_GRAY,
    DARK_GRAY,
    YELLOW,
    LIGHT_YELLOW,
    ORANGE,
    LIGHT_ORANGE,
    DARK_ORANGE,
    PURPLE,
    LIGHT_PURPLE,
    DARK_PURPLE,
    PINK,

    BLUE_GRADIENT,
    LIGHT_BLUE_GRADIENT,
    DARK_BLUE_GRADIENT,
    CYAN_GRADIENT,
    GREEN_GRADIENT,
    LIGHT_GREEN_GRADIENT,
    DARK_GREEN_GRADIENT,
    RED_GRADIENT,
    LIGHT_RED_GRADIENT,
    DARK_RED_GRADIENT,
    GRAY_GRADIENT,
    LIGHT_GRAY_GRADIENT,
    DARK_GRAY_GRADIENT,
    YELLOW_GRADIENT,
    LIGHT_YELLOW_GRADIENT,
    ORANGE_GRADIENT,
    LIGHT_ORANGE_GRADIENT,
    DARK_ORANGE_GRADIENT,
    PURPLE_GRADIENT,
    LIGHT_PURPLE_GRADIENT,
    DARK_PURPLE_GRADIENT,
    PINK_GRADIENT;





}
